-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le :  mar. 30 nov. 2021 à 12:22
-- Version du serveur :  10.1.29-MariaDB
-- Version de PHP :  7.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `distribpc`
--

-- --------------------------------------------------------

--
-- Structure de la table `produits`
--

CREATE TABLE `produits` (
  `id_produit` int(11) NOT NULL,
  `id_categorie` int(11) NOT NULL,
  `id_souscategorie` int(11) NOT NULL,
  `marque` varchar(100) DEFAULT NULL,
  `nom_produit` varchar(22) DEFAULT NULL,
  `prix` decimal(6,2) DEFAULT NULL,
  `description_courte` varchar(50) DEFAULT NULL,
  `description` varchar(1000) DEFAULT NULL,
  `num_reference` varchar(30) DEFAULT NULL,
  `disponible` varchar(10) DEFAULT NULL,
  `meilleur_vente` varchar(100) DEFAULT NULL,
  `promo` varchar(10) DEFAULT NULL,
  `pourcentage_promo` int(11) DEFAULT NULL,
  `garantit` varchar(100) DEFAULT 'sans garantit',
  `image_produit` varchar(1000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `produits`
--

INSERT INTO `produits` (`id_produit`, `id_categorie`, `id_souscategorie`, `marque`, `nom_produit`, `prix`, `description_courte`, `description`, `num_reference`, `disponible`, `meilleur_vente`, `promo`, `pourcentage_promo`, `garantit`, `image_produit`) VALUES
(1, 1, 1, 'Distribpc', 'Dynamite', '999.99', 'Avec un Ryzen 7 3700X et une GeForce RTX 3060 sous', 'Avec un Ryzen 7 3700X et une GeForce RTX 3060 sous le capot, on peut clairement affirmer que ce PC Dynamite n\'est pas là pour trier les lentilles ! Une machine capable du meilleur en HD comme en 2K, et avec beaucoup de classe.', '1234', 'disponible', 'NULL', 'NULL', 0, '3ans', 'pc_fixe1.jpg'),
(2, 1, 2, 'MSI', 'GS66 Stealth', '749.99', 'Le PC Portable MSI GS66 Stealth 10UE-214FR fait pa', 'Le PC Portable MSI GS66 Stealth 10UE-214FR fait partie des premiers portables à accueillir la nouvelle génération de carte NVIDIA Ampere. Il vous propose une configuration qui se dote ainsi d\'une RTX 3060, accompagnée par un processeur Intel Core i7 Comet Lake, 16 Go de RAM et un stockage ultra réactif de 1 To au format SSD. Une véritable machine à jouer qui, avec son écran IPS 300 Hz, devrait vous en mettre plein les yeux !', '1235', 'pas dispo', 'true', NULL, NULL, '3ans', 'pc_portable4.jpg'),
(3, 3, 3, 'Samsung', 'Odyssey G3 S24AG300NU', '199.00', 'Les écrans PC Samsung Odyssey représentent une ass', 'Les écrans PC Samsung Odyssey représentent une association entre un design futuriste et une performance certaine pour vous accompagner dans votre quotidien de gamer. Avec sa dalle en technologie VA cadencée à 144 Hz et sa résolution Full HD, vous avez trouvé le partenaire de votre immersion dans vos jeux favoris !', '1236', 'disponible', 'true', 'true', 20, '2ans', 'ecran2.jpg'),
(4, 2, 12, 'Gainward', 'GeForce RTX 3060 Ti', '799.00', 'Point d\'entrée idéal pour les technologies NVIDIA ', 'Point d\'entrée idéal pour les technologies NVIDIA RTX, la carte graphique Gainward GeForce RTX 3060 Ti Ghost LHR vous permet de jouer en 1080p, tout en profitant du ray-tracing ! Optimisée par Ampere, l\'architecture NVIDIA RTX de seconde génération, vous profitez non seulement d\'un gain de puissance brute par rapport à la génération précédente, mais également des améliorations apportées aux technologies de ray tracing et DLSS.', '1237', 'disponible', 'true', NULL, NULL, '2ans', 'carte_graphique2.jpg'),
(5, 2, 12, 'Gigabyte', 'GeForce RTX 3060 Ti', '769.00', 'Propulsez votre configuration PC gamer dans le mon', 'Propulsez votre configuration PC gamer dans le monde du 1080p sans compromis avec la carte graphique Gigabyte GeForce RTX 3060 Ti GAMING OC ! Optimisée par Ampere, l\'architecture NVIDIA RTX de seconde génération, vous profitez non seulement d\'un gain de puissance brute par rapport à la génération précédente, mais également des améliorations apportées aux technologies de ray tracing et DLSS.', '1238', 'disponible', NULL, NULL, NULL, '2ans', 'carte_graphique3.jpg'),
(6, 1, 1, 'Distribpc', 'Backstab', '1099.99', 'Avec son couple infernal Ryzen 5 5600X et GeForce ', 'Avec son couple infernal Ryzen 5 5600X et GeForce RTX 3060, ce PC Backstab va rapidement faire l\'objet de nombreuses convoitises chez les gamers ... Une machine ultra moderne portée par 2 composants au sommet de leur art.', '1239', 'disponible', NULL, NULL, NULL, '2ans', 'pc_fixe2.jpg'),
(7, 3, 6, 'Logitech', 'G502 HERO - Lol K/DA E', '69.00', 'La souris gaming Logitech G502 HERO utilise un cap', 'La souris gaming Logitech G502 HERO utilise un capteur optique d\'une précision de 16 000 DPI ainsi que 11 boutons programmables et un système de poids modulables. Cette nouvelle version de la désormais légendaire G502 reprend tout ce qui a fait le charme des itérations précédentes tout en se mettant à jour avec le capteur Logitech HERO ! Elle revient donc... mais encore plus performante !', '1240', 'disponible', NULL, NULL, NULL, '2ans', 'souris3.jpg'),
(8, 3, 7, 'Bird', 'UM1 - Blanc', '69.00', 'Le microphone Bird UM1 présente l\'avantage d\'être ', 'Le microphone Bird UM1 présente l\'avantage d\'être totalement plug-and-play en USB. Sa directivité cardioïde le rend parfait pour tout streamer ou youtuber qui souhaite se professionaliser avec un microphone abordable et de qualité.', '1241', 'disponible', NULL, NULL, NULL, '3ans', 'micro1.jpg'),
(9, 3, 4, 'Logitech', 'G533 Prodigy', '119.00', 'Le casque gaming Logitech G533 Prodigy offre une v', 'Le casque gaming Logitech G533 Prodigy offre une virtualisation du son en 7.1 pour obtenir une expérience bluffante de réalisme dans vos jeux au quotidien. Performant, ce casque est également équipé d\'un micro avec filtre anti-pop pour une clarté absolue de vos conversations !', '1242', 'disponible', 'true', NULL, NULL, '3ans', 'casque1.jpg'),
(10, 3, 4, 'Logitech', 'G433 - Noir', '74.95', 'Le casque gaming Logitech G433 est l\'arme ultime p', 'Le casque gaming Logitech G433 est l\'arme ultime pour les joueurs qui ne souhaitent pas s\'encombre d\'un casque de jeu et d\'un casque nomade. Précis en 7.1 virtuel avec un micro détachable certifié Discord, bénéficiez d\'une qualité de son parfaite où que vous soyez !', '1243', 'disponible', NULL, 'true', 28, '3ans', 'casque4.jpg'),
(11, 2, 11, 'Gigabyte', 'X570 AORUS XTREME', '149.00', 'Processeurs AMD Ryzen 3000, Gigabyte propose sa ca', 'Avec l\'arrivée du chipset X570 et des processeurs AMD Ryzen 3000, Gigabyte propose sa carte mère X570 AORUS Xtreme alliant qualité de fabrication et fonctionnalités étendues pour satisfaire vos envies gaming ! Parmi les premières à prendre en charge la technologie PCIe 4.0, qui offre une bande passante doublée par rapport au 3.0, cette carte mère rassemble l\'essentiel pour monter votre nouvelle configuration de jeu.', '1244', 'pas dispo', 'true', 'NULL', 0, '3ans', 'carte_mere5.jpg'),
(12, 3, 3, 'MSI', 'Optix G271', '219.98', 'L\'écran gaming MSI Optix G271 a été conçu pour les', 'L\'écran gaming MSI Optix G271 a été conçu pour les personnes à la recherche d\'un écran performant pour le gaming. Cet écran large dispose d\'une dalle IPS de 27 pouces en résolution Full HD (1920 x 1080 pixels), d\'un taux de rafraîchissement de 144 Hz ainsi que d\'un temps de réponse très réduit de seulement 1 ms ! Il allie fluidité et rapidité pour une réactivité hors-norme. Sa dalle IPS lui permet d\'afficher des images comprenant des couleurs plus profondes avec un meilleur contraste. Il possède la technologie FreeSync qui vous plongera dans une immersion totale lors de vos sessions gaming, en éliminant tout tearing ou stuttering pour une fluidité sans précédent !', '1238', 'disponible', 'true', 'true', 20, '2ans', 'ecran10.jpg'),
(13, 3, 3, 'MSI', 'Creator PS321QR', '769.98', 'Le moniteur MSI Creator PS321QR s\'affirme par son ', 'Le moniteur MSI Creator PS321QR s\'affirme par son excellence. Pensé pour les créateurs de contenu, il propose des caractéristiques techniques premium avec sa dalle Rapid-IPS de 31,5 pouces à la résolution WQHD (2560 x 1440 pixels). Affichage au format 16:9 et prise en charge du HDR600 assurent un affichage large et de qualité. Sa conception design et de qualité, intègre des options d\'ergonomie avancées et s\'intègre à merveille à votre environnement de travail. Le plus du produit : les nombreuses fonctionnalités proposées par l\'outil MSI Creator OSD.', '1239', 'disponible', NULL, NULL, 0, '2ans', 'ecran11.jpg'),
(14, 3, 3, 'MSI', 'Optix G241', '229.96', 'Le moniteur MSI Creator PS321QR s\'affirme par son ', 'Le moniteur MSI Creator PS321QR s\'affirme par son excellence. Pensé pour les créateurs de contenu, il propose des caractéristiques techniques premium avec sa dalle Rapid-IPS de 31,5 pouces à la résolution WQHD (2560 x 1440 pixels). Affichage au format 16:9 et prise en charge du HDR600 assurent un affichage large et de qualité. Sa conception design et de qualité, intègre des options d\'ergonomie avancées et s\'intègre à merveille à votre environnement de travail. Le plus du produit : les nombreuses fonctionnalités proposées par l\'outil MSI Creator OSD.', '1239', 'disponible', NULL, 'true', 21, '2ans', 'ecran7.jpg'),
(15, 2, 12, 'MSI', 'GeForce RTX 3080 Ti', '2229.95', 'La carte graphique MSI GeForce RTX 3080 Ti SUPRIM ', 'Carte graphique MSI GeForce RTX 3080 Ti SUPRIM X 12G (LHR) - Autre vuePhotos non contractuelles\r\nLa carte graphique MSI GeForce RTX 3080 Ti SUPRIM X rassemble performances, silence et design pour les amateurs de jeux vidéos PC. Optimisée par Ampere, l\'architecture NVIDIA RTX de seconde génération, vous profitez non seulement d\'un gain de performances excellent pour une expérience de jeu en 4K UHD ultra-fluide, mais également des technologies de ray tracing et DLSS optimisées pour une immersion encore plus grande.', '1238', 'disponible', NULL, 'true', 20, '5ans', 'carte_graphique7.jpg'),
(16, 2, 12, 'NVIDIA', 'GeForce RTX 2060 Dual ', '569.95', 'ASUS nous propose sa nouvelle carte graphique haut', 'ASUS nous propose sa nouvelle carte graphique haut de gamme gaming NVIDIA : voici l\'Asus GeForce RTX 2060 Dual OC EVO. Elle débarque avec toutes les technologies arrivées avec l\'architecture Turing de Nvidia (DLSS, Ray Tracing) et dans un format compact idéal pour les joueurs cherchant à créer une configuration compacte très performante.Carte graphique MSI GeForce RTX 3080 Ti SUPRIM X 12G (LHR) - Autre vue\r\nCarte graphique MSI GeForce RTX 3080 Ti SUPRIM X 12G (LHR) - Autre vue\r\nCarte graphique MSI GeForce RTX 3080 Ti SUPRIM X 12G (LHR) - Autre vue\r\nCarte graphique MSI GeForce RTX 3080 Ti SUPRIM X 12G (LHR) - Autre vuePhotos non contractuelles\r\nLa carte graphique MSI GeForce RTX 3080 Ti SUPRIM X rassemble performances, silence et design pour les amateurs de jeux vidéos PC. Optimisée par Ampere, l\'architecture NVIDIA RTX de seconde génération.', '1239', 'disponible', NULL, NULL, NULL, '5ans', 'carte_graphique4.jpg'),
(17, 3, 5, 'Logitech', 'G513 - GX Brown', '159.95', 'Le clavier gamer Logitech G513 intègre des interru', 'Le clavier gamer Logitech G513 intègre des interrupteurs GX Brown ainsi qu\'un rétro-éclairage personnalisable, le tout avec une finition en alu à couper le souffle. Ne faites aucunes concessions, que ce soit sur la performance ou sur le style !', '1240', 'disponible', 'true', 'true', 25, '5ans', 'clavier1.jpg'),
(18, 1, 1, 'Distribpc', 'Airstrike [ PC Gamer ]', '1449.90', 'Une nouvelle mouture de notre PC Gamer best-seller', 'Une nouvelle mouture de notre PC Gamer best-seller Airstrike, avec cette fois-ci un processeur Ryzen 7 3700X couplé à la petite bombe Radeon RX 6600. Performance, fiabilité, modernité ... tout y est.', '1241', 'disponible', NULL, 'true', 10, '3ans', 'pc_fixe5.jpg'),
(19, 1, 1, 'Distribpc', 'Fury', '1249.90', 'Le gaming PC est en plein chaos en cette année', 'Le gaming PC est en plein chaos en cette année 2021 et pourtant quelques pépites surgissent. Le PC Fury c\'est un Ryzen 5 3600 et une GeForce RTX 2060 qui bossent de concert pour vous offrir un maximum de puissance en 1080p. Attention, il n\'y en aura pas pour tout le monde.', '1241', 'disponible', NULL, NULL, 0, '3ans', 'pc_fixe3.jpg'),
(20, 1, 2, 'DELL', 'XPS 13 9305-161', '1049.99', 'L\'ultra portable Dell XPS 13 9305-161, avec un for', 'L\'ultra portable Dell XPS 13 9305-161, avec un format très compact proche d\'un 12 pouces, mise sur une mobilité extrême.. Il dispose d\'un châssis en fibre de carbone pour un poids total de 1,29 Kg seulement... Inutile d\'argumenter, vous êtes déjà séduits !', '1244', 'disponible', 'true', NULL, NULL, '3ans', 'pc_portable3.jpg'),
(21, 2, 10, 'AMD', 'Ryzen 5 5600X', '369.95', 'Le processeur AMD Ryzen 5 5600X profite des amélio', 'Le processeur AMD Ryzen 5 5600X profite des améliorations apportées par l\'architecture AMD Zen 3. Performances énergétiques revues à la hausse, fréquences plus élevées, cache L3 unifié par blocs de 32 Mo et un processeur qui perpétue la tradition AMD Ryzen d\'excellence en termes de haute performance par watt : voici un sérieux nombre d\'arguments pour le faire rejoindre votre future configuration PC gamer !', '1245', 'disponible', NULL, NULL, NULL, '3ans', 'processeur1.jpg'),
(22, 2, 10, 'INTEL', 'Core i7 12700K', '529.99', 'Le processeur Intel Core i7-12700K fait partie de ', 'Le processeur Intel Core i7-12700K fait partie de la 12ème génération de processeurs Intel Alder Lake, il profite d\'un architecture hybride et d\'un boost de fréquence, ainsi que du support de la norme PCIe 5.0 et de la mémoire DDR5 pour une configuration PC Gamer tournée vers le futur. Que vous soyez gamer ou créateur de contenu multimedia, la performance et au rendez-vous !', '1246', 'disponible', NULL, NULL, NULL, '3ans', 'processeur2.jpg'),
(23, 2, 10, 'AMD', 'Ryzen 7 3700X', '327.95', '8 coeurs, 3,60 GHz, 32 Mo, AMD Ryzen, 65 Watts', 'Le processeur AMD Ryzen 7 3700X de 3ème génération arrive, en mettant à profit la nouvelle architecture Zen 2 gravée en 7nm ce sont d\'excellentes performances qui vous attendent ainsi qu\'une efficacité énergétique améliorée. Il se positionne dans le haut de gamme des Ryzen 3000 avec ses 8 coeurs / 16 threads et sa fréquence max de 4.4 GHz. Votre allié idéal pour du jeu vidéo extrême ou bien pour des applications de création graphique gourmandes !', '1246', 'disponible', 'true', NULL, NULL, '3ans', 'processeur3.jpg'),
(24, 3, 5, 'Roccat', 'Vulcan TKL Roccat Tita', '125.99', 'Le clavier mécanique Roccat Vulcan TKL est équipé ', 'Le clavier mécanique Roccat Vulcan TKL est équipé en interrupteurs exclusifs Roccat Titan Speed, qui disposent d\'un retour linéaire et d\'une course réduite de 1,4 mm seulement. Son cadre en aluminium anodisé, son éclairage RGB et son format compact en font un clavier qui allie aussi bien la performance que la robustesse et l\'esthétisme !', '9999', 'disponible', 'NULL', 'true', 38, '2ans', 'clavier6.jpg'),
(25, 3, 5, 'Logitech', 'G915 TKL Lightspeed', '229.96', 'Le clavier gamer Logitech G915 TKL intègre des int', 'Le clavier gamer Logitech G915 TKL intègre des interrupteurs GL ainsi qu\'un rétro-éclairage personnalisable, le tout avec une finition en alu à couper le souffle. Sans-fil et ultra-fin, combinez performance, ergonomie et esthétique !', '9998', 'disponible', 'true', NULL, 0, '5ans', 'clavier2.jpg'),
(30, 1, 1, 'ASUS', 'E5 AiO 24 E5402WHAK-BA', '1149.00', 'L\'ordinateur tout-en-un ASUS ExpertCenter E5 AiO 2', 'L\'ordinateur tout-en-un ASUS ExpertCenter E5 AiO 24 est performant et facile à utiliser par les professionnels. Il vient à bout des tâches les plus poussées afin de vous faire gagner du temps et de l\'argent. Il fournit une puissance de calcul élevée grâce à son processeur Intel Core i5-11500B, 8 Go de mémoire DDR4 et sa connectique complète incluant le nouveau Thunderbolt 4.0. En plus d\'arborer un design ultra-compact et élégant, il accueille un SSD 256 Go et une connectivité Wi-Fi AX afin de répondre aux besoins actuels et futurs de votre entreprise.', '9969', 'disponible', 'NULL', 'NULL', 0, '5ans', 'pc_fixe6.jpg'),
(31, 3, 3, 'Philips', 'Momentum', '699.95', 'Dalle 43\" MVA, résolution 4K UHD, HDR, éclairage A', 'Dalle 43\" MVA, résolution 4K UHD, HDR, éclairage Ambiglow, le moniteur Philips Momentum 436M6VBPAB vous réserve un spectacle immersif ! Appréciez des couleurs éclatantes, fidèles et naturelles, une puissance sonore de 2 x 7 Watts et un temps de réponse de 4 ms.', '436', 'disponible', 'true', 'NULL', 0, '5ans', 'ecran13.jpg'),
(32, 1, 1, 'Apple', 'iMac (2021)', '2494.00', 'Transfiguré par la puce Apple M1, l\'iMac 24 pouces', 'Transfiguré par la puce Apple M1, l\'iMac 24 pouces est prodigieusement fin et cumule les talents. Il a été imaginé pour se démarquer où qu\'il soit, tout en s\'intégrant parfaitement à votre mode de vie.', '6549', 'disponible', 'NULL', 'NULL', 0, '5ans', 'pc_fixe7.jpg'),
(33, 3, 4, 'Sennheiser', 'HD', '179.94', 'Vous êtes à la recherche d\'un casque avec un son h', 'Vous êtes à la recherche d\'un casque avec un son haute qualité ? Le Sennheiser HD 599 répondra à vos attentes avec sa conception circum-auriculaire ouverte, ses transducteurs avec technologie exclusive E.A.R. et un port très confortable composé d\'oreillettes douces et d\'un arceau rembourré.', '599', 'disponible', 'NULL', 'true', 27, '2ans', 'casque7.jpg'),
(34, 2, 11, 'MSI', 'B550M PRO-VDH', '105.95', 'Embarquant le chipset AMD B550, la carte mère MSI ', 'Embarquant le chipset AMD B550, la carte mère MSI B550M PRO-VDH avec son socket AM4 est conçue pour accueillir les processeurs AMD Ryzen à partir de la troisième génération. Elle permettra de composer une configuration Gaming disposant des dernières avancées technologiques', '0002', 'disponible', 'true', 'NULL', 0, '2ans', 'carte_mere6.jpg'),
(35, 2, 16, 'MSI', 'MAG FORGE 100M', '64.96', 'Conçu pour délivrer d\'excellentes performances, le', 'Conçu pour délivrer d\'excellentes performances, le boîtier gaming MSI MAG FORGE 100M peut compter sur ses 3 ventilateurs de 120 mm inclus pour refroidir votre machine efficacement. Il peut accueillir une carte graphique de 330 mm maximum et propose un magnifique rétroéclairage RGB !', '0003', 'disponible', 'true', 'NULL', 0, '2ans', 'boitier6.jpg'),
(36, 1, 2, 'LG', 'gram 16', '1455.00', 'Déplacez-vous en toute liberté avec le PC portable', 'Déplacez-vous en toute liberté avec le PC portable LG gram 16. A la fois mince et performant, ce notebook LG gram vous permettra de travailler efficacement sans négliger votre confort d\'utilisation grâce à son grand écran de niveau professionnel', '(16Z90P-G.AA75F)', 'disponible', 'NULL', 'NULL', 0, '5ans', 'pc_portable6.jpg'),
(37, 1, 2, 'Razer', 'Blade 14', '2555.00', 'Gagnez en puissance, en confort et en mobilité ave', 'Gagnez en puissance, en confort et en mobilité avec le Razer Blade 14 ! Ce PC portable Gamer offre de hautes performances de jeu et offre un excellent confort d\'utilisation avec son écran QHD 165 Hz et son clavier rétroéclairé Razer Chroma !', '(RZ09-0370BFA3-R3F1)', 'disponible', 'NULL', 'NULL', 0, '5ans', 'pc_portable7.jpg'),
(38, 3, 8, 'Edifier', 'R1280DB Bois', '109.96', 'Discrètes et modernes, les enceintes 2.0 Edifier R', 'Discrètes et modernes, les enceintes 2.0 Edifier R1280DB réservent un son précis et profond avec une puissance RMS de 42 watts. Disposant de la technologie Bluetooth, vous allez pouvoir diffuser facilement votre playlist du moment et ainsi faire profiter votre entourage d\'un son incroyablement net.', 'R1280DB', 'disponible', 'true', NULL, 0, '2ans', 'enceinte1.jpg'),
(39, 3, 8, 'Logitech', 'Multimedia Speakers Z2', '36.95', 'Avec une puissance de crête de 10 watts, les haut-', 'Avec une puissance de crête de 10 watts, les haut-parleurs Logitech Z200 Multimedia Speakers au design moderne offrent un son riche et clair. Deux transducteurs par haut-parleur génèrent un son stéréo équilibré et une acoustique impeccable pour une immersion sonore totale.', '0005', 'disponible', 'true', NULL, 0, '2ans', 'enceinte2.jpg'),
(40, 3, 6, 'Logitech', 'MX Vertical', '109.94', 'Avec son design né de la science et des performanc', 'Avec son design né de la science et des performances élevées de la série MX de Logitech, la souris MX Vertical est une souris ergonomique conçue pour offrir précision, contrôle et confort aux utilisateurs expérimentés.', '0006', 'disponible', 'true', 'NULL', 0, '1ans', 'souris1.jpg'),
(41, 3, 6, 'Logitech', 'G G502 Lightspeed', '119.95', 'Disposant d\'une conception sans fil avec technolog', 'Disposant d\'une conception sans fil avec technologie Lightspeed, la Logitech G502 Lightspeed fera de vous une machine redoutable et redoutée. En effet, elle est équipée d\'un capteur optique HERO de 16000 dpi pour une précision et une réactivité optimale.', '0007', 'disponible', 'true', 'NULL', 0, '1ans', 'souris5.jpg'),
(42, 3, 6, 'Logitech ', 'G G502 Hero', '59.95', 'Conçue pour vous offrir des niveaux de personnalis', 'Conçue pour vous offrir des niveaux de personnalisation inégalés, la Logitech G502 Hero fera de vous une machine redoutable et redoutée. En effet, elle est équipée d\'un capteur optique de 16000 dpi pour une précision et une réactivité optimale.', '0008', 'disponible', 'true', 'NULL', 0, '1ans', 'souris2.jpg'),
(43, 3, 6, 'Logitech', 'G G502 Hero (LoL K/DA)', '69.95', 'Conçue pour vous offrir des niveaux de personnalis', 'Conçue pour vous offrir des niveaux de personnalisation inégalés, la Logitech G502 Hero fera de vous une machine redoutable et redoutée. En effet, elle est équipée d\'un capteur optique de 16000 dpi pour une précision et une réactivité optimale.', '0009', 'disponible', 'true', 'NULL', 0, '2ans', 'souris4.jpg'),
(45, 2, 9, 'G.Skill', 'Trident Z5 RGB', '445.55', 'La mémoire DDR5 de la série Trident Z5 RGB de G.Sk', 'La mémoire DDR5 de la série Trident Z5 RGB de G.Skill est la mémoire phare de G.SKILL conçue pour des performances extrêmes sur les plates-formes DDR5 de nouvelle génération. Dotée d\'un dissipateur thermique en aluminium plus élégant et rationalisé, disponible en argent métallique ou en noir mat.', 'F5-5600U3636C16GX2-TZ5RK', 'disponible', 'NULL', 'NULL', 0, '2ans', 'memoire2.jpg'),
(46, 2, 9, 'G.Skill', 'Aegis', '79.96', 'La mémoire Aegis a été conçue pour s\'adapter à mer', 'La mémoire Aegis a été conçue pour s\'adapter à merveille sur des plateformes Intel de dernier cri dotées de processeurs Intel Core comme la sixième génération. L\'objectif ? Offrir le plus de souplesse possible aux joueurs chevronnés', 'F4-3200C16D-16GIS', 'disponible', 'true', 'NULL', 0, '2ans', 'memoire3.jpg'),
(47, 2, 12, 'Sapphire', 'NITRO+ Radeon RX 6700 ', '968.19', 'Carte graphique PCI-Express overclockée - Avec bac', 'Carte graphique PCI-Express overclockée - Avec backplate - Compatible VR + 1 mois d\'abonnement Xbox Game Pass offert !', '11306-01-20G', 'pas dispo', 'NULL', 'NULL', 0, '2ans', 'carte_graphique8.jpg'),
(49, 2, 12, 'Gigabyte', 'Radeon RX 6600 EAGLE', '599.95', 'Propulsez votre configuration PC gamer dans le mon', 'Propulsez votre configuration PC gamer dans le monde du 1080p sans compromis avec la carte graphique Gigabyte Radeon RX 6600 EAGLE ! S\'appuyant sur 8 Go de mémoire GDDR6, l\'Infinity Cache, ainsi que sur le savoir-faire AMD en terme d\'efficacité énergétique, cette carte graphique est prête à intégrer votre configuration PC gaming.', '0010', 'disponible', 'NULL', 'NULL', 0, '2ans', 'carte_graphique9.jpg'),
(50, 3, 7, 'FIFINE', 'Microphone', '79.99', 'Array à trois capsules Fournit un son de diffusion', 'Array à trois capsules Fournit un son de diffusion légendaire. Quatre modèles de capteurs Les modèles de capteurs cardioïdes, omnidirectionnels, bidirectionnels et stéréo offrent une flexibilité incroyable, vous permettant d\'enregistrer d\'une manière qui nécessiterait normalement plusieurs microphones.\r\nPlug\'n Play sur Mac et PC - Démarrez instantanément l\'enregistrement et la diffusion en continu sur Mac ou PC. Sortie USB, connectez-vous directement à votre ordinateur via le câble USB inclus.\r\nLe microphone d\'enregistrement au design époustouflant présente un design visuel inspiré de l\'équipement audio classique - un design métallique élégant qui complètera tout système de bureau, la couleur noire métallique pour correspondre à l\'esthétique de votre caméra.\r\nVolume du casque et coupure du micro: contrôlez le volume du son dans vos écouteurs et appuyez sur le bouton de mise en sourdine pour les moments où vous avez besoin de tousser ou d\'éternuer.\r\nMicrophone Gain, Pickup Pattern Switc', '0011', 'disponible', 'true', 'NULL', 0, '2ans', 'micro5.jpg'),
(51, 3, 7, 'HyperX', 'Quadcast S', '199.99', 'Le microphone RGB HyperX Quadcast S se compose de ', 'Le microphone RGB HyperX Quadcast S se compose de trois condensateurs de 14 mm pour un enregistrement parfait de votre voix ! Son système anti-vibrations intégré en fait un micro idéal pour vos sessions de stream ou de podcast, sans avoir besoin d\'un bras articulé !', '0012', 'disponible', 'NULL', 'NULL', 0, '1ans', 'micro2.jpg'),
(52, 3, 7, 'Elgato', 'Wave 3', '185.00', 'Le microphone Elgato Wave: 3 vous offre une soluti', 'Le microphone Elgato Wave: 3 vous offre une solution de mixage de qualité, qui allie simplicité d\'utilisation, avec notamment un bouton multifonction plus que pratique, et qualité sonore professionnelle. Offrez ainsi un contenu toujours plus qualitatif à votre public !', '0013', 'disponible', 'NULL', 'NULL', 0, '1ans', 'micro3.jpg'),
(53, 3, 7, 'Razer', 'Seiren Mini - Noir', '66.85', 'Le microphone USB Razer Seiren Mini offre une solu', 'Le microphone USB Razer Seiren Mini offre une solution de capture audio de qualité avec une directivité supercardioïde dans un format compact. Très facile d\'installation et d\'utilisation, branchez-le en USB et gagnez en interactivité avec votre voix retranscrite parfaitement sans les bruits environnants !', '0014', 'disponible', 'true', 'NULL', 0, '1ans', 'micro4.jpg'),
(54, 3, 3, 'Aorus', 'FI27Q-X', '749.95', 'Grâce au moniteur gaming Aorus FI27Q-X, vous allez', 'Grâce au moniteur gaming Aorus FI27Q-X, vous allez pouvoir transporter votre expérience de jeu vers les sommets ! Mettez ainsi toutes les chances de votre côté pour obtenir la victoire avec des performances à la hauteur de vos objectifs et une qualité visuelle exceptionnelle.', '0016', 'disponible', 'true', 'true', 15, '2ans', 'ecran6.jpg'),
(55, 1, 1, 'HP', 'Pavilion 27-D1251NF', '1650.99', 'L\'ordinateur tout-en-un HP Pavilion 27-d1251nf ave', 'L\'ordinateur tout-en-un HP Pavilion 27-d1251nf avec son écran UHD de 27 pouces est conçu travailler sur les projets exigeants. Il est équipé d\'un processeur Intel Core i7-11700T associé à 16 Go de mémoire Ram et à une carte graphique NVIDIA GeForce MX350. Sa Webcam et ses connectivités Bluetooth 5.0 et Wi-Fi AC permettront de répondre à tous vos besoins. Le clavier et la souris sans fil sont fournis.', '0015', 'disponible', 'NULL', 'NULL', 0, '5ans', 'pc_fixe8.jpg'),
(56, 1, 1, 'Distribpc', 'Backstab [ Win11 - PC ', '1774.00', 'Avec son couple infernal Ryzen 5 5600X et GeForce', 'Avec son couple infernal Ryzen 5 5600X et GeForce RTX 3060, ce PC Backstab va rapidement faire l\'objet de nombreuses convoitises chez les gamers ... Une machine ultra moderne portée par 2 composants au sommet de leur art.', '0016', 'disponible', 'NULL', 'NULL', 0, '2ans', 'pc_fixe9.jpg'),
(57, 2, 15, 'Fox spirit', 'PM18 - 960 Go', '135.95', 'Photos non contractuelles\r\nLe disque SSD Fox Spiri', 'Photos non contractuelles\r\nLe disque SSD Fox Spirit PM18 améliore considérablement la réactivité de votre système actuel avec des vitesses de démarrage, de chargement et de transfert par rapport aux disques durs mécaniques. Animé par un contrôleur de dernière génération offrant des vitesses de lecture et d\'écriture allant jusqu\'à 3500 Mo/s et 3000 Mo/s (2 To), ce SSD est jusqu\'à 7 fois plus rapide qu\'un disque SSD traditionnel (SATA/AHCI) et offre des performances plus élevées, un multi-tasking ultra réactif, et accélère l\'ensemble du système.', '0017', 'disponible', 'true', 'NULL', 0, '2ans', 'ssd1.jpg'),
(58, 2, 15, 'Textorm', 'B5 - 120 Go', '25.95', 'Le disque SSD Textorm B5 améliore considérablement', 'Le disque SSD Textorm B5 améliore considérablement la réactivité de votre système actuel avec des vitesses de démarrage, de chargement et de transfert par rapport aux disques durs mécaniques. Animé par un contrôleur de la dernière génération offrant des vitesses de lecture et d\'écriture allant jusqu\'à 550 Mo/s et 500 Mo/s, ce SSD est dix fois plus rapide qu\'un disque dur traditionnel et offre des performances plus élevées, un multi-tasking ultra réactif, et accélère l\'ensemble du système.', '0018', 'disponible', 'true', 'NULL', 0, '2ans', 'ssd2.jpg'),
(59, 2, 15, 'Aorus', 'M.2 Gen 4 Black - 500 ', '114.95', 'Aorus revient dans le monde des SSD avec un SSD Ge', 'Aorus revient dans le monde des SSD avec un SSD Gen 4 en M.2 plus classique dans son aspect, plus sobre que son grand frère cuivré. De la performance avec le dernier contrôleur Phison E16, de la fiabilité avec le support du ECC RAID et de la vitesse avec le trie des puces Nand Toshiba de qualité BiCS64 96 couches 3D TLC ; tout pour jouer comme vous aimez.', '0019', 'disponible', 'NULL', 'NULL', 0, '2ans', 'ssd3.jpg'),
(60, 2, 15, 'Kingston', 'A400 - 480 Go', '54.95', 'Le disque SSD A400 Kingston améliore considérablem', 'Le disque SSD A400 Kingston améliore considérablement la réactivité de votre système actuel avec des vitesses de démarrage, de chargement et de transfert plus élevées par rapport aux disques durs mécaniques. Animé par un contrôleur de la dernière génération offrant des vitesses de lecture et d\'écriture allant jusqu\'à 500 Mo/s et 350 Mo/s, ce SSD est dix fois plus rapide qu\'un disque dur1 traditionnel et offre des performances plus élevées, un multi-tasking ultra réactif, et accélère l\'ensemble du système.', '0019', 'disponible', 'true', 'NULL', 0, '2ans', 'ssd4.jpg');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `produits`
--
ALTER TABLE `produits`
  ADD PRIMARY KEY (`id_produit`),
  ADD KEY `FK_produits_categorie` (`id_categorie`),
  ADD KEY `FK_produits_souscategorie` (`id_souscategorie`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `produits`
--
ALTER TABLE `produits`
  MODIFY `id_produit` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=61;

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `produits`
--
ALTER TABLE `produits`
  ADD CONSTRAINT `FK_produits_categorie` FOREIGN KEY (`id_categorie`) REFERENCES `categorie` (`id_categorie`),
  ADD CONSTRAINT `FK_produits_souscategorie` FOREIGN KEY (`id_souscategorie`) REFERENCES `souscategorie` (`id_souscategorie`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
